name: Generate JSON Schema

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  generate-and-upload-schema:
    name: Generate and Upload Rules JSON Schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version-file: pyproject.toml
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Generate JSON Schema for Rules
        run: poetry run python -m feedly_regexp_marker gen-json-schema-for-rules > rules.schema.json

      - name: Upload JSON Schema to Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.event.release.tag_name }} rules.schema.json --clobber
