name: Lint and test

on:
  pull_request:
  push:
    branches: ["main"]
    tags: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version-file: pyproject.toml
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Run flake8
        run: make flake8

      - name: Run mypy
        run: make mypy

      - name: Run pytest
        run: make pytest
